language: python

python:
  - "3.8"

addons:
  apt:
    packages:
      - openjdk-8-jre

before_install:
  - pip install awscli pipenv

install:
  - pipenv install --system --ignore-pipfile 

jobs:
  include:
    - stage: build
      script: ./shell-scripts/build.sh
    - stage: verify
      script: ./shell-scripts/verify.sh
    - stage: deploy
      script: ./shell-scripts/deploy.sh
