language: python

python:
  - "3.8"

addons:
  apt:
    packages:
      - openjdk-8-jre

install:
  - pip install pipenv
  - pipenv install --system --ignore-pipfile 

jobs:
  include:
    - stage: build
      script: pipenv run make clean && pipenv run make build -j
    - stage: verify
      script: pipenv run make verify
    - stage: deploy
      script: echo "Deploy yet to be implemented"
